name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 5.3.1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  permission_handler: any
  uuid: any
  flutter:
    sdk: flutter
  flutter_joybuttons: ^1.0.3
  flutter_joystick: ^0.0.4
  flutter_reactive_ble: ^5.3.1
  platform_device_id_v3: ^1.0.0
  functional_data: ^1.0.0
  intl: ^0.19.0

  provider: ^6.0.1

  reactive_ble_platform_interface: ^5.3.1
  meta: any
dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^4.0.0
  flutter_lints: any
  flutter_test:
    sdk: flutter
  functional_data_generator: ^2.1.0

flutter:
  uses-material-design: true